### ISSUE TITLE
Touch Gestures

### ISSUE THREAD

**Issue by git-moss** [electraone/firmware#24]
Since the Electra One has a touch screen, I was wondering if it would be possible to implement some touch gestures (as known from phones and tablets).
E.g.:
- swipe left / right could be used to switch pages
- swipe up could show the pages menu
- swipe down could show the presets menu

**Comment by electraone** [comment]
It is technically possible and I tested that in the past. Good implementation of gestures requires, however, screen animations. (swipe effect, etc). The reason is that people are used to it from tables and phones. I eventually decided not to go in that direction. I must say that your idea of touch gestures on knobs feels much more attractive and E1 friendly.
